# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 985a2b1b6f0fd7ea9bd51f7229fe36274014326b99e9e63ecb71cc370068397c373aa52e5b6380e6dafefdafa32ee0b8a9dcd726da6cd4ca689b03c7acd7d00a

test:
  secret_key_base: 1b97391dfa185e7440469f229d7d2f156292e26c7512e0a2d0932db9e3b2f12bc9bc9a70dd0583111b99018571c0d1683b2ac8c8c29ea2a7706bf894499fa634

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
